package:
  name: coolprop
  version: 6.6.0
  top-level:
    - CoolProp

source:
  url: https://files.pythonhosted.org/packages/13/88/35c88960cf20cf483f1e2127ad999fce4528451ad37173064cdcb3834ebf/CoolProp-6.6.0.tar.gz
  sha256: cf6fad704b3ae00f4df309cfd1e2ee48d155886b569a73f2cc38a57eda463082
  extract_dir: source

  extras:
    - - extras/setup.py
      - ./setup.py
    - - extras/pyproject.toml
      - ./pyproject.toml

requirements:
  run:
    - numpy
    - matplotlib

test:
  imports:
    - CoolProp
    - CoolProp.GUI
    - CoolProp.Plots

about:
  home: http://www.coolprop.org
  PyPI: https://pypi.org/project/CoolProp
  summary: "Open-source thermodynamic and transport properties database"
  license: MIT
